name: Publish Chronicle
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Build Chronicle

    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.0
        with:
          username: 'RobbieLD'
          reponame: 'chronicle'
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          VUE_APP_MOVIE_DB_KEY: ${{ secrets.MOVIE_DB_KEY }}
          VUE_APP_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          VUE_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          VUE_APP_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          VUE_APP_FIREBASE_STOREAGE_BUCKET: ${{ secrets.FIREBASE_STOREAGE_BUCKET }}
          VUE_APP_FIREBASE_MESSAGE_SENDER_ID: ${{ secrets.FIREBASE_MESSAGE_SENDER_ID }}
          VUE_APP_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
